name: Cypress Component Tests

on: 
  pull_request:
    branches:
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Cypress component tests
<<<<<<< HEAD
        run: nnpx cypress run --component
=======
        run: npx cypress run --component
>>>>>>> a6e500358bce31a3ae25cf6d8941856bd5bd153e
