name: Cypress Component Tests

on: 
  pull_request:
    branches:
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: cypress-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Install Cypress Binary
        run: npx cypress install --force

      - name: Verify Cypress Installation
        run: npx cypress info

      - name: Run Cypress component tests
        run: npx cypress run --component
