name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RENDER_DEPLOY_HOOK: "${{ secrets.RENDER_DEPLOY_HOOK }}"
    steps:
      - name: Trigger Deploy on Render
        run: curl -X POST "$RENDER_DEPLOY_HOOK"
